### ISSUE TITLE
Repo link gives a 404

### ISSUE THREAD

**Issue by jnielson94** [kale-stew/all-talks#4]
Hi Kylie! Excellent talk today! Thanks a ton :) 

I was going to check out the sample-server that you mentioned at the end, but the link gives a 404 - perhaps it's still a private repo?

Thanks!
https://github.com/kale-stew/talks/blob/master/evolution-of-an-api/slides/src/presentation.js#L518
links to
https://github.com/kale-stew/sample-server

**Comment by kale-stew** [comment]
Hi! You can check out the functional repo at https://www.github.com/kale-stew/simple-server
